export const ActionTypes = {
  SET_CURRENT_USER_DETAILS: "SET_CURRENT_USER_DETAILS",
  SET_USER_LOCATION: "SET_USER_LOCATION",
  // SET_USER_NAME: "SET_USER_NAME",
  // SET_USER_AGE: "SET_USER_AGE",
  // SET_USER_GENDER: "SET_USER_GENDER",
  // SET_USER_INTEREST1: "SET_USER_INTEREST1",
  // SET_USER_INTEREST2: "SET_USER_INTEREST2",
  // SET_USER_EMAIL: "SET_USER_EMAIL",
  // SET_USER_USERNAME: "SET_USER_USERNAME",
  // SET_USER_DISPLAY_NAME: "SET_USER_DISPLAY_NAME",
  // SET_USER_AVATAR_URI: "SET_USER_AVATAR_URI",
};
